### PR TITLE
JavaScript/TypeScript version of the library

### PR DESCRIPTION
**Pull request by athewsey**
*Issue #, if available:* #14

*Description of changes: **(UPDATED)***

A JavaScript/TypeScript port of Textract Response Parser to go along with the current Python and C# tooling: Ready for use in both server-side (NodeJS) and client-side (in-browser, ES6) environments.

While early drafts of this PR were a fairly direct port of the TRPv1 Python library into JavaScript, the current version modifies the APIs somewhat - recognising that:

- Python and JS/TS have different conventions, built-ins, and relationships with JSON de/serialization.
- Python TRP is in some flux between TRPv1 and TRPv2. While we can leverage some lessons learned, it may not be possible or practical to fully align to the v2 API and maintain full feature parity (which I believe the C# library already doesn't?)

**Notable features & design choices:**

- Page content orientation back-ported from TRPv2 as `page.getModalWordOrientationDegrees()`
- Improved reading-order logic in `page.getLineClustersInReadingOrder()` gives better results as evidenced on the `test/data/multicol-test-document.png` synthetic sample
- More properties are pulled directly through from underlying API JSON, providing a more stable base to expand the scope of mutation (edit) operations through TRP.
- Array properties are generally removed in favour of iterators (like `page.iterLines()`) and indexers (like `document.pageNumber()`) and where still available return `slice()` copies: To clarify that we can't support arbitrary mutations of the arrays just yet.
- We define our own type system for the underlying Textract API responses in `api-models.ts`, to avoid introducing dependency on `@aws-sdk/textract-client`, and offer more specific/detailed typings in some cases... So an `as` cast may be needed to initially load in your JSON in TypeScript apps.

Feedback very welcome!

<br/><br/>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by CGarces** [comment]
Hi.

Any hint about the usage of this PR?

**Comment by athewsey** [comment]
I actually created this because I was building a custom task UI for Sagemaker Ground Truth, to annotate Textract results... So was using the same JS code inline in a task template HTML - But could imagine ideally it might be useful as a utility in NodeJS based services/functions, or as a properly packaged browser JS library for client side apps... Not quite sure if that answers the question?

**Comment by CGarces** [comment]
I'm trying to use it inside an typescript/angular project with AWS Amplify, but I have no idea about how get "a properly packaged browser JS library for client side".

**Comment by athewsey** [comment]
Sorry @CGarces I responded on mobile and assumed you were a maintainer asking for the reasoning behind the PR! 😂

Since this was only a draft to gauge interest, because I needed something simple for a project, it's only rough and not:

- Hosted on NPM yet, or
- Packaged with TypeScript types (just JS), or
- Automatically linted/transpiled to check it uses only older features of JS (to be sure it works in older browsers)

...So if you want to include it in a TypeScript front-end project today, you'd probably be best off just copying the `index.js` file into your project as e.g. `trp.js` (there are no dependencies currently in `package.json`) and then figuring out how to import it.

If it works for you, I believe there's an [allowJs compiler option](https://stackoverflow.com/a/56909179) you could turn on to enable the import? Otherwise, you might have to create a `trp.d.ts` type declaration file for TypeScript... which I've done manually before, but [looks like there might be an automated way?](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).

It's great to hear somebody else is interested in the draft, and good feedback that it needs refactoring to support TypeScript for more use cases: So I'll try to find some time to update this PR if I can to make things easier, but unfortunately can't promise a timescale at the moment!

**Comment by athewsey** [comment]
OK well, quicker than expected but there's a first draft!

You should be able to:
- Bring `src/index.ts` directly in to your TypeScript project, e.g. as `trp.ts`, **or**
- Run `npm run build` to build JavaScript (plus a type declaration file) and then use those - the JS is not minified at the moment

Regardless of how you import the library, it works basically the same as the Python TRP at high level... (Except I had to rename the `Document` class to avoid conflict in browsers)

You initialize a `TextractDocument` with either a Textract API response JSON, or a list of them (e.g. if the response was split into multiple parts with `NextToken`)... Then you can access the high-level APIs of the document e.g:

```js
const doc = TextractDocument(myResponseJson);
const dobField = doc.pages[0].form.getFieldByKey("DateOfBirth:");
// ...etc
```

I haven't reconciled the typing used in this draft with the AWS SDK for JS yet, so assuming you're using that to call Textract from the client, you'll probably have to coerce the type of the Textract JSON to make it work - something like `TextractDocument(myResponseJson as ApiResponsePage)`

**Comment by athewsey** [comment]
Just added first round of unit tests (and fixed that `.pages` was not visible as a property of the top level Document class)

**Pull request merged**
